package SkyLine

import "fmt"

func Template(InputData string) {
	template_Block1 := `
	package main

	/////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//																										   //
	//								 Generated by the SkyLine interpreter 									   //

	import (
		"flag"
		"fmt"
		Mod "main/Modules/SkyLine_Backend"
		Server "main/Modules/SkyLine_Server"
		"os"
		"path/filepath"
		"runtime"
		"time"
	)
	
	func init() {
		flag.Parse()
	}
	
	func main() {
		// DATA BLOCK 
		%s 
		if x := Mod.RunAndParseNoFile(Data); x != nil {
			fmt.Fprintln(os.Stderr, x)
			os.Exit(0)
		}
	}
	`
	data := InputData
	template_Block1 = fmt.Sprintf(template_Block1, data)
	// start file manipulation and output from here.

}
